# docker-compose to deploy multiple collectors
version: '3.3'

services:

  ukraine_admin2_tessellation:
    container_name: ukraine_admin2_tessellation
    volumes:
      - ./ukraine_admin2_tessellation:/app/in
      - ./../../../data/monty/ukraine_admin2_tessellation:/app/data
    build:
      args:
        sleep_time: 0
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure
