# docker-compose to deploy multiple collectors onto saffron
version: '3.1'

services:

  ukraine_regions:
    container_name: ukraine_regions
    volumes:
      - ./../../data/ukraine_regions:/app/data
      - ./ukraine_regions/specs:/app/specs
      - ./ukraine_regions/credentials.csv:/app/credentials.csv
      - ./ukraine_regions/.env:/app/.env
    build:
      context: ../../../
      dockerfile: ./deploy/docker/Dockerfile
    command: cron -f; source /app/utils/launch.sh
    restart: unless-stopped
