# example docker-compose to deploy one or more collections on a virtual machine
version: '3.3'

services:

  example_collection:
    container_name: example_collection
    volumes:
      - ./../../../data/_example_collector/_example_collection:/app/data
    build:
      args:
        collection_dir: "./docker/collectors/_example_collector/_example_collection"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: unless-stopped
