# example docker-compose to deploy one or more collections on a virtual machine
version: '3.3'

services:

  example_collection:
    container_name: example_collection
    volumes:
      - ./_example_collection:/app/in
      - ./../../../data/_example_collector/_example_collection:/app/data
    build:
      args:
        sleep_time: 12
        pysocialwatcher_opt_flag: "false"
        collection_dir: "./docker/collectors/_example_collector/_example_collection"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: unless-stopped
