# docker-compose to deploy multiple collectors
version: '3.3'

services:

  venezuelan_exodus:
    container_name: venezuelan_exodus
    volumes:
      - ./venezuelan_exodus:/app/in
      - ./../../../data/mingo/venezuelan_exodus:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: unless-stopped

#  ukraine_qcri:
#    container_name: ukraine_qcri
#    volumes:
#      - ./ukraine_qcri:/app/in
#      - ./../../../data/mingo/ukraine_qcri:/app/data
#    build:
#      args:
#        collection_dir: "./docker/collectors/mingo/ukraine_qcri"
#      context: ./../../../
#      dockerfile: ./docker/collectors/Dockerfile
#    restart: unless-stopped
