# docker-compose to deploy one or multiple collectors (i.e. services)
version: '3.3'

services:

  dgg_national:
    container_name: dgg_national
    volumes:
      - ./dgg_national:/app/in
      - ./../../../data/badger/dgg_national:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  dgg_national_ins:
    container_name: dgg_national_ins
    volumes:
      - ./dgg_national_ins:/app/in
      - ./../../../data/badger/dgg_national_ins:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure


