# docker-compose to deploy multiple collectors
version: '3.3'

services:

  crawler:
    container_name: crawler
    network_mode: host
    volumes:
      - ./../../data:/app/data
      - .env:/app/.env
    build:
      context: ./../../
      dockerfile: ./docker/crawler/Dockerfile
    restart: unless-stopped

