# docker-compose to deploy multiple collectors

services:

  crawler:
    network_mode: host
    volumes:
      - ./../../data:/app/data
      - .env:/app/.env
    build:
      context: ./../../
      dockerfile: ./docker/crawler/Dockerfile
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 15

