# docker-compose to deploy multiple collectors
version: '3.3'

services:

  crawler:
    network_mode: host
    volumes:
      #- ./../../data:/app/data
      - /research/nowpop/meta_collections/venezuela_qcri:/app/data
      - .env:/app/.env
    build:
      context: ./../../
      dockerfile: ./docker/crawler/Dockerfile
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 15

