FROM nginx:latest

# Create necessary directories
RUN mkdir -p /usr/share/nginx/html \
    && mkdir -p /etc/letsencrypt/live \
    && mkdir -p /etc/letsencrypt/archive

# Copy the Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose ports 80 and 443
EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]