FROM nginx:latest

# Create necessary directories
RUN mkdir -p /usr/share/nginx/html \
    && mkdir -p /etc/letsencrypt/live \
    && mkdir -p /etc/letsencrypt/archive

# Expose ports 80 and 443
EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]