# docker-compose to deploy one or multiple collectors (i.e. services)
version: '3.3'

services:

  baseline:
    container_name: baseline
    volumes:
      - ./baseline:/app/in
      - ./../../../data/jubal/baseline:/app/data
    build:
      args:
        sleep_time: 0
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: unless-stopped
