services:

  baseline_homerecent:
    container_name: baseline_homerecent
    volumes:
      - ./baseline_homerecent:/app/in
      - ./../../../data/jubal/baseline_homerecent:/app/data
    build:
      args:
        sleep_time: 2
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  baseline_priority_homerecent:
    container_name: baseline_priority_homerecent
    volumes:
      - ./baseline_priority_homerecent:/app/in
      - ./../../../data/jubal/baseline_priority_homerecent:/app/data
    build:
      args:
        sleep_time: 2
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure
