# docker-compose to deploy multiple collectors
version: '3.3'

services:

  ukraine_regions:
    container_name: ukraine_regions
    volumes:
      - ./../../../data/ukraine_regions:/app/data
    build:
      args:
        collection_dir: "./docker/virtual_machines/saffron/ukraine_regions"
      context: ./../../../
      dockerfile: ./deploy/docker/virtual_machines/Dockerfile
    restart: unless-stopped

  ukraine_neighbours1:
    container_name: ukraine_neighbours1
    volumes:
      - ./../../../data/ukraine_neighbours1:/app/data
    build:
      args:
        collection_dir: "./docker/virtual_machines/saffron/ukraine_neighbours1"
      context: ./../../../
      dockerfile: ./docker/virtual_machines/Dockerfile
    restart: unless-stopped

  ukraine_neighbours2:
    container_name: ukraine_neighbours2
    volumes:
      - ./../../../data/ukraine_neighbours2:/app/data
    build:
      args:
        collection_dir: "./docker/virtual_machines/saffron/ukraine_neighbours2"
      context: ./../../../
      dockerfile: ./docker/virtual_machines/Dockerfile
    restart: unless-stopped

  ukraine_language:
    container_name: ukraine_language
    volumes:
      - ./../../../data/ukraine_language:/app/data
    build:
      args:
        collection_dir: "./docker/virtual_machines/saffron/ukraine_language"
      context: ./../../../
      dockerfile: ./docker/virtual_machines/Dockerfile
    restart: unless-stopped

  ukraine_europe:
    container_name: ukraine_europe
    volumes:
      - ./../../../data/ukraine_europe:/app/data
    build:
      args:
        collection_dir: "./docker/virtual_machines/saffron/ukraine_europe"
      context: ./../../../
      dockerfile: ./docker/virtual_machines/Dockerfile
    restart: unless-stopped

  ukraine_countries:
    container_name: ukraine_countries
    volumes:
      - ./../../../data/ukraine_countries:/app/data
    build:
      args:
        collection_dir: "./docker/virtual_machines/saffron/ukraine_countries"
      context: ./../../../
      dockerfile: ./docker/virtual_machines/Dockerfile
    restart: unless-stopped
