services:

  rus_exodus_facebook:
    container_name: rus_exodus_facebook
    volumes:
      - ./rus_exodus_facebook:/app/in
      - ./../../../data/niska/rus_exodus_facebook:/app/data
    build:
      args:
        sleep_time: 11
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: unless-stopped

  rus_exodus_instagram:
    container_name: rus_exodus_instagram
    volumes:
      - ./rus_exodus_instagram:/app/in
      - ./../../../data/niska/rus_exodus_instagram:/app/data
    build:
      args:
        sleep_time: 11
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: unless-stopped
