# docker-compose to deploy multiple collectors
version: '3.3'

services:

  rus_exodus_facebook:
    container_name: rus_exodus_facebook
    volumes:
      - ./../../../data/niska/rus_exodus_facebook:/app/data
    build:
      args:
        collection_dir: "./docker/collectors/niska/rus_exodus_facebook"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: unless-stopped

  rus_exodus_instagram:
    container_name: rus_exodus_instagram
    volumes:
      - ./../../../data/niska/rus_exodus_instagram:/app/data
    build:
      args:
        collection_dir: "./docker/collectors/niska/rus_exodus_instagram"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: unless-stopped
