services:

  ukraine_regions_homerecent:
    container_name: ukraine_regions_homerecent
    volumes:
      - ./ukraine_regions_homerecent:/app/in
      - ./../../../data/saffron/ukraine_regions_homerecent:/app/data
    build:
      args:
          sleep_time: 11
          email_notification_enable: "True"
          email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  ukraine_neighbours_homerecent:
    container_name: ukraine_neighbours_homerecent
    volumes:
      - ./ukraine_neighbours_homerecent:/app/in
      - ./../../../data/saffron/ukraine_neighbours_homerecent:/app/data
    build:
      args:
          sleep_time: 11
          email_notification_enable: "True"
          email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  ukraine_language_homerecent:
    container_name: ukraine_language_homerecent
    volumes:
      - ./ukraine_language_homerecent:/app/in
      - ./../../../data/saffron/ukraine_language_homerecent:/app/data
    build:
      args:
          sleep_time: 11
          email_notification_enable: "True"
          email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  ukraine_europe_homerecent:
    container_name: ukraine_europe_homerecent
    volumes:
      - ./ukraine_europe_homerecent:/app/in
      - ./../../../data/saffron/ukraine_europe_homerecent:/app/data
    build:
      args:
          sleep_time: 11
          email_notification_enable: "True"
          email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: unless-stopped

