# example docker-compose to deploy one or more collections on a virtual machine
version: '3.3'

services:
  example_collection:
    container_name: example_collection
    volumes:
      - ./../../data/example_virtual_machine/example_collection:/app/data
    build:
      args:
        virtual_machine: example_virtual_machine
        collection: example_collection
      context: ../../../
      dockerfile: ./deploy/docker/Dockerfile
    restart: unless-stopped
