# example docker-compose to deploy one or more collections on a virtual machine
version: '3.1'

services:
  example_collection:
    container_name: example_collection
    build:
      context: ../../../
      dockerfile: ./deploy/docker/Dockerfile
    volumes:
      - ./example_collection/data:/app/data
      - ./example_collection/specs:/app/specs
      - ./example_collection/credentials.csv:/app/credentials.csv
      - ./example_collection/.env:/app/.env
    command: cron -f; source /app/utils/launch.sh
    restart: unless-stopped
