services:

  global_migration:
    container_name: global_migration_core
    volumes:
      - ./global_migration_core:/app/in
      - ./../../../data/serenity/global_migration_core:/app/data
    build:
      args:
          sleep_time: 2
          email_notification_enable: "True"
          email_receiver: "douglas.leasure@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: unless-stopped

