# docker-compose to deploy multiple collectors
version: '3.3'

services:

  israeli_conflict:
    container_name: israeli_conflict
    volumes:
      - ./israeli_conflict:/app/in
      - ./../../../data/stitch/israeli_conflict:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  gaza_cities:
    container_name: gaza_cities
    volumes:
      - ./gaza_cities:/app/in
      - ./../../../data/stitch/gaza_cities:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  westbank_cities:
    container_name: westbank_cities
    volumes:
      - ./westbank_cities:/app/in
      - ./../../../data/stitch/westbank_cities:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: always

  israeli_cities:
    container_name: israeli_cities
    volumes:
      - ./israeli_cities:/app/in
      - ./../../../data/stitch/israeli_cities:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: always

#  turkey_earthquake:
#    container_name: turkey_earthquake
#    volumes:
#      - ./turkey_earthquake:/app/in
#      - ./../../../data/stitch/turkey_earthquake:/app/data
#    build:
#      context: ./../../../
#      dockerfile: ./docker/collectors/Dockerfile
#    restart: on-failure

#  turkey_language:
#    container_name: turkey_language
#    volumes:
#      - ./turkey_language:/app/in
#      - ./../../../data/stitch/turkey_language:/app/data
#    build:
#      context: ./../../../
#      dockerfile: ./docker/collectors/Dockerfile
#    restart: on-failure

#  sudan_conflict:
#    container_name: sudan_conflict
#    volumes:
#      - ./sudan_conflict:/app/in
#      - ./../../../data/stitch/sudan_conflict:/app/data
#    build:
#      context: ./../../../
#      dockerfile: ./docker/collectors/Dockerfile
#    restart: on-failure

