services:

  gaza_governorates_homerecent:
    container_name: gaza_governorates_homerecent
    volumes:
      - ./gaza_governorates_homerecent:/app/in
      - ./../../../data/stitch/gaza_governorates_homerecent:/app/data
    build:
      args:
        sleep_time: 2
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  gaza_municipalities_homerecent:
    container_name: gaza_municipalities_homerecent
    volumes:
      - ./gaza_municipalities_homerecent:/app/in
      - ./../../../data/stitch/gaza_municipalities_homerecent:/app/data
    build:
      args:
        sleep_time: 2
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  gaza_cities_homerecent:
    container_name: gaza_cities_homerecent
    volumes:
      - ./gaza_cities_homerecent:/app/in
      - ./../../../data/stitch/gaza_cities_homerecent:/app/data
    build:
      args:
        sleep_time: 11
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  israeli_conflict_homerecent:
    container_name: israeli_conflict_homerecent
    volumes:
      - ./israeli_conflict_homerecent:/app/in
      - ./../../../data/stitch/israeli_conflict_homerecent:/app/data
    build:
      args:
        sleep_time: 11
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  westbank_cities_homerecent:
    container_name: westbank_cities_homerecent
    volumes:
      - ./westbank_cities_homerecent:/app/in
      - ./../../../data/stitch/westbank_cities_homerecent:/app/data
    build:
      args:
        sleep_time: 11
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: always

  israeli_cities_homerecent:
    container_name: israeli_cities_homerecent
    volumes:
      - ./israeli_cities_homerecent:/app/in
      - ./../../../data/stitch/israeli_cities_homerecent:/app/data
    build:
      args:
        sleep_time: 11
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: always

  lebanon_cities_homerecent:
    container_name: lebanon_cities_homerecent
    volumes:
      - ./lebanon_cities_homerecent:/app/in
      - ./../../../data/stitch/lebanon_cities_homerecent:/app/data
    build:
      args:
        sleep_time: 11
        email_notification_enable: "True"
        email_receiver: "douglas.leasure@demography.ox.ac.uk,edith.darin@demography.ox.ac.uk"
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: always
