# docker-compose to deploy multiple collectors
version: '3.3'

services:

  turkey_earthquake:
    container_name: turkey_earthquake
    volumes:
      - ./turkey_earthquake:/app/in
      - ./../../../data/stitch/turkey_earthquake:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  turkey_language:
    container_name: turkey_language
    volumes:
      - ./turkey_language:/app/in
      - ./../../../data/stitch/turkey_language:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  sudan_conflict:
    container_name: sudan_conflict
    volumes:
      - ./sudan_conflict:/app/in
      - ./../../../data/stitch/sudan_conflict:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure

  israeli_conflict:
    container_name: israeli_conflict
    volumes:
      - ./israeli_conflict:/app/in
      - ./../../../data/stitch/israeli_conflict:/app/data
    build:
      context: ./../../../
      dockerfile: ./docker/collectors/Dockerfile
    restart: on-failure
