# docker-compose to deploy multiple collectors
version: '3.3'

services:

  rus_exodus_facebook:
    container_name: rus_exodus_facebook
    volumes:
      - ./../../../data/rus_exodus_facebook:/app/data
    build:
      args:
        collection_dir: "./deploy/docker/virtual_machines/niska/rus_exodus_facebook"
      context: ../../../../
      dockerfile: ./deploy/docker/virtual_machines/Dockerfile
    restart: unless-stopped

  rus_exodus_instagram:
    container_name: rus_exodus_instagram
    volumes:
      - ./../../../data/rus_exodus_instagram:/app/data
    build:
      args:
        collection_dir: "./deploy/docker/virtual_machines/niska/rus_exodus_instagram"
      context: ../../../../
      dockerfile: ./deploy/docker/virtual_machines/Dockerfile
    restart: unless-stopped
