# docker-compose to deploy one or multiple collectors (i.e. services)
version: '3.3'

services:

  dgg_national:
    container_name: dgg_national
    volumes:
      - ./../../../data/dgg_national:/app/data
    build:
      args:
        collection_dir: "./deploy/docker/virtual_machines/badger/dgg_national"
      context: ./../../../../
      dockerfile: ./deploy/docker/virtual_machines/Dockerfile
    restart: unless-stopped
